// ********RoostGPT********
/*
Test generated by RoostGPT for test demoTestGitlab using AI Type Open AI and AI Model gpt-4

Test generated for /v1/accounts/{account-Id}/transactions_get for http method type GET in rest-assured framework

RoostTestHash=2b28de8802


*/

// ********RoostGPT********
package org.commonjava.maven.ext.RoostTest;

import io.restassured.RestAssured;
import io.restassured.response.Response;
import io.restassured.response.ValidatableResponse;
import org.junit.jupiter.api.Test;

import java.io.BufferedReader;
import java.io.FileReader;
import java.io.File;
import java.io.IOException;
import java.util.HashMap;
import java.util.Map;

import static io.restassured.RestAssured.given;
import static org.hamcrest.Matchers.*;

public class transactionsGetTest {

    @Test
    public void transactionsGet_Test() {
        RestAssured.baseURI = System.getenv("BASE_URL");

        // Read CSV file
        try (BufferedReader reader = new BufferedReader(new FileReader("src" + File.separator + "test" + File.separator + "java" + File.separator + "org" + File.separator + "commonjava" + File.separator + "maven" + File.separator + "ext" + File.separator + "RoostTest" + File.separator + "transactionsGetTest.csv"))) {
            String headerLine = reader.readLine();
            String[] headers = headerLine.split(",");

            String line;
            while ((line = reader.readLine()) != null) {
                String[] data = line.split(",");

                // Create a map of header to data
                Map<String, String> map = new HashMap<>();
                for (int i = 0; i < headers.length; i++) {
                    map.put(headers[i], data[i]);
                }

                Response response = given()
                        .pathParams(map)
                        .when()
                        .get("/v1/accounts/{account-Id}/transactions")
                        .then()
                        .extract().response();

                switch (response.statusCode()) {
                    case 200:
                        System.out.println("Description: Success");
                        break;
                    case 400:
                        validateErrorResponse(response);
                        break;
                    case 404:
                        validateNotFoundResponse(response);
                        break;
                    case 422:
                        validateUnprocessableEntityResponse(response);
                        break;
                    default:
                        System.out.println("Unknown status code received");
                }
            }
        } catch (IOException e) {
            e.printStackTrace();
        }
    }

    private void validateErrorResponse(Response response) {
        ValidatableResponse validatableResponse = response.then();
        validatableResponse.assertThat().body("error", is("Bad Request"));
        validatableResponse.assertThat().body("message", notNullValue());
    }

    private void validateNotFoundResponse(Response response) {
        ValidatableResponse validatableResponse = response.then();
        validatableResponse.assertThat().body("error", is("Not Found"));
        validatableResponse.assertThat().body("message", notNullValue());
    }

    private void validateUnprocessableEntityResponse(Response response) {
        ValidatableResponse validatableResponse = response.then();
        validatableResponse.assertThat().body("error", is("Unprocessable Entity"));
        validatableResponse.assertThat().body("message", notNullValue());
    }
}
